[package]
name = "pak"
version = "0.1.0"
edition.workspace = true

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0"
flate2 = { version = "1.0", features = ["zlib"] }
serde = { version = "1.0", features = ["derive"] }
zip = { version = "8.1", default-features = false, features = ["deflate"] }
