[package]
name = "pam"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.4"
anyhow = "1.0"
thiserror = "1.0"
bitflags = "2.10.0"
serde_json = "1.0.149"
