[package]
name = "compiledtext"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror = "1.0"
flate2 = { version = "1.0", features = ["zlib"] }
simple-rijndael = "0.3.2"
md5 = "0.7"
hex = "0.4"
base64 = "0.22"
byteorder = "1.5.0"
